# Generated by Django 4.1.5 on 2023-01-17 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dressapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catagory',
            new_name='Category',
        ),
    ]
